name 'testwebapp'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures testwebapp'
long_description 'Installs/Configures testwebapp'
version '0.1.0'
